CREATE DATABASE clinic;
CREATE TABLE  patients (id SERIAL PRIMARY KEY, name VARCHAR(50), date_of_birth DATE);
CREATE TABLE  medical_histories (id SERIAL PRIMARY KEY, admitted_at  TIMESTAMP, patient_id INT, status VARCHAR(50));
ALTER TABLE medical_histories ADD CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patients(id);
CREATE TABLE invoices (id SERIAL PRIMARY KEY, total_amount DECIMAL, generated_at TIMESTAMP, payed_at TIMESTAMP, medical_history_id INT);
ALTER TABLE invoices ADD CONSTRAINT fk_medical_history_id FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id);
CREATE TABLE invoices_items (id SERIAL PRIMARY KEY, unit_price DECIMAL, quantity INT, total_price DECIMAL, invoice_id INT,treatment_id INT);
ALTER TABLE invoices_items ADD CONSTRAINT fk_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(id);
CREATE TABLE treatments (id SERIAL PRIMARY KEY, type VARCHAR(50), name VARCHAR(50));
ALTER TABLE invoices_items ADD CONSTRAINT fk_treatment_id FOREIGN KEY (treatment_id) REFERENCES treatments(id);
CREATE TABLE treatments (id SERIAL PRIMARY KEY, type VARCHAR(50), name VARCHAR(50));
ALTER TABLE invoices_items ADD CONSTRAINT fk_treatment_id FOREIGN KEY (treatment_id) REFERENCES treatments(id);
CREATE TABLE medical_histories_treatment (medical_history_id INT REFERENCES medical_histories(id), treatment_id INT REFERENCES treatments(id));
CREATE INDEX idx_patients_name ON patients(name);
CREATE INDEX idx_medical_histories_patient_id ON medical_histories(patient_id);
CREATE INDEX idx_invoices_medical_history_id ON invoices(medical_history_id);
CREATE INDEX idx_invoices_items_invoice_id ON invoices_items(invoice_id);
CREATE INDEX idx_invoices_items_treatment_id ON invoices_items(treatment_id);
CREATE INDEX idx_treatments_name ON treatments(name);